[package]
name = "line_tools"
version = "0.1.0"
edition = "2024"
authors = [
  "Kostiantyn Mysnyk <wandalen@obox.systems>",
  "Avramenko Yevhenii <yevhenii.av@obox.systems>"
]
license = "MIT"
repository = "https://github.com/Wandalen/cgtools"
description = "A library for rendering lines."
keywords = ["line"]

[lints]
workspace = true

[features]
default = []

[dependencies]
minwebgl = { workspace = true }
ndarray_cg = { workspace = true }
mod_interface = { workspace = true }
serde = { workspace = true, features = [ "derive" ] }

[dev-dependencies]
test_tools = { workspace = true }
